services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/property_user_db
    depends_on:
      - db
    command: bee run 
    networks:
      - default
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    container_name: postgres_container_property_users
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: property_user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgres_data: